language: node_js
sudo: false
addons:
  code_climate:
    repo_token: 'TODO'
install:
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
cache:
  directories:
    - 'node_modules'
